# Simple test pipeline that runs quickly for testing purposes
name: Simple Test Pipeline

trigger: none  # Manual trigger only for testing

pool: server

steps:
  - task: Delay@1
    inputs:
      delayForMinutes: '0'