[project]
name = "ado-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]

[tool.uv]
dev-dependencies = [
    "pytest-cov>=6.2.1",
    "pytest-xdist>=3.8.0",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-n auto"
