version: '3'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - uv sync

  test:
    desc: Run project tests
    cmds:
      - ./run_tests.sh

  coverage:
    desc: Generate code coverage report
    cmds:
      - AZURE_DEVOPS_EXT_PAT=$(security find-generic-password -w -a ado-token) ADO_ORGANIZATION_URL="https://dev.azure.com/RussellBoley" uv run pytest --cov=ado_client --cov-report=term-missing

  serve:
    desc: Run the FastAPI application
    cmds:
      - uv run uvicorn main:app --reload
    env:
      PYTHONPATH: .
