version: '3'

env:
  AZURE_DEVOPS_EXT_PAT: $(security find-generic-password -w -a ado-token)
  ADO_ORGANIZATION_URL: 'https://dev.azure.com/RussellBoley'
  ADO_PROJECT_NAME: "Learning"
  PYTHONPATH: "."

tasks:
  init:
    cmds:
      - echo "AZURE_DEVOPS_EXT_PAT=$AZURE_DEVOPS_EXT_PAT\r\nADO_ORGANIZATION_URL=$ADO_ORGANIZATION_URL" >> .env
  install:
    desc: Install project dependencies
    cmds:
      - uv sync
    sources:
      - pyproject.toml
    generates:
      - uv.lock
      - .venv/pyvenv.cfg

  test:
    desc: Run project tests
    cmds:
      - uv run pytest -v

  coverage:
    desc: Generate code coverage report
    cmds:
      -  uv run pytest -v --cov

  run:
    desc: Run the FastAPI application
    cmds:
      - uv run python server.py

  inspect:
    desc: Run the MCP Inspector on the server
    deps:
      - task: install
    cmds:
      - fastmcp dev server.py

  auth-test:
    desc: test your ado token
    cmds:
      - curl -s -u ":$AZURE_DEVOPS_EXT_PAT" "$ADO_ORGANIZATION_URL/_apis/ConnectionData?api-version=7.1-preview" | jq .