version: '3'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - uv sync

  test:
    desc: Run project tests
    cmds:
      - ./run_tests.sh

  serve:
    desc: Run the FastAPI application
    cmds:
      - uv run uvicorn main:app --reload
    env:
      PYTHONPATH: .
